### ISSUE TITLE
Add Guide on how to add/structure new files

### ISSUE THREAD

**Issue by martinheidegger** [pnext/samples#1]
We need information on the data-sets we add:

- [x] License
- [x] Creator
- [ ] Creation Date

I assume a structure like `<data>/<set-name>/<format>`? Do we need more information?

**Comment by iosefa** [comment]
oops. I added some data to a develop branch but I didnt see your comment above @martinheidegger. Anyway, I will add more documentation next week and can change the file structure if necessary.

**Comment by iosefa** [comment]
closing this issue for now as it was resolved in #2 . however, this can be reopened if more documentation is needed.
